// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt7hgf9EHEchC9J0n9ScBAm4CzzUssklk',
    appId: '1:358500086074:web:e8c493d95edbe3b4e46003',
    messagingSenderId: '358500086074',
    projectId: 'flutter-test001-54056',
    authDomain: 'flutter-test001-54056.firebaseapp.com',
    storageBucket: 'flutter-test001-54056.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVz_ML-1a7CeS-iSogF-YgsgKwqYXzfL4',
    appId: '1:358500086074:android:5856cf5bb4d0f1b1e46003',
    messagingSenderId: '358500086074',
    projectId: 'flutter-test001-54056',
    storageBucket: 'flutter-test001-54056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuRIl1sXA6sTJ3EMOul97vHLjE29-YOQM',
    appId: '1:358500086074:ios:22b6ac235c92e680e46003',
    messagingSenderId: '358500086074',
    projectId: 'flutter-test001-54056',
    storageBucket: 'flutter-test001-54056.appspot.com',
    iosClientId: '358500086074-qkq8nu22e7j2274siraprgscoeh379ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLockAuth01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuRIl1sXA6sTJ3EMOul97vHLjE29-YOQM',
    appId: '1:358500086074:ios:c4cf51a4e344a6bfe46003',
    messagingSenderId: '358500086074',
    projectId: 'flutter-test001-54056',
    storageBucket: 'flutter-test001-54056.appspot.com',
    iosClientId: '358500086074-qq4co5it9rf0a0osi980sgr35lm7j9bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLockAuth01.RunnerTests',
  );
}
